AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
      - 'db/**/*'
      - '.git/**/*'
      - 'Gemfile'
      - 'index.rb'
      - 'spec/*'
